---
- name: Ensure nginx is installed and in working state
  apt: 
    name: nginx
    update_cache: yes
    state: latest
    
# - name: Serve index.html
#   copy:
#     src: ../files
#     dest: /var/www/html
  
- name: Copy Nginx configuration
  copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes