---
- name: Install HAProxy
  apt:
    name: haproxy

- name: Config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: 
    - Restart HAProxy

- name: start HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: HAProxy exporter setup shrshryo-1
  docker_container:
    name: haproxy_exporter
    image: quay.io/prometheus/haproxy-exporter:v0.9.0
    ports:
      - "9101:9101"
    command: --haproxy.scrape-uri="http://{{ inventory_hostname }}:88/haproxy?stats;csv"
    restart_policy: always

- name: start HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes