---
- name: Install Grafana
  apt:
    name:
      - adduser
      - libfontconfig1

- name: Download
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.2.1_amd64.db
    dest: /tmp/grafana_7.2.1_amd64.db

- name: Install
  apt:
    deb: /tmp/grafana_7.2.1_amd64.db

- name: Start
  service:
    name: grafana-server
    state: started
    enabled: yes