---
- name: Install Grafana
  apt:
    name:
      - adduser
      - libfontconfig1

- name: Download
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.2.2_amd64.deb
    dest: /tmp/grafana_7.2.2_amd64.deb

- name: Install
  apt:
    deb: /tmp/grafana_7.2.2_amd64.deb

- template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
    - Restart Grafana

- name: Enabled
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Add backup to group grafana
  user:
    name: backup
    groups: grafana
    append: yes
