{
 "title": "Grafana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory consumption",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable" }
   ]
  },
  {
   "title": "Bind Query",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "keepalived_up" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "MySQL_Up",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "nginx_up",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "bind_up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bind_up",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "keepalived VRRP State",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "keepalived_vrrp_state" }
   ]
  },
  {
   "title": "MySQL Status ID",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "MySQL server read only status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only"
    }
   ]
  },
  {
   "title": "haproxy_up",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "Bind Query",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bind_resolver_queries_total" }
   ]
  },
  {
   "title": "MySQL Status ID",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "MySQL Status ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "keepalived_vrrp_state",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "keepalived_vrrp_state" }
   ]
  },
  {
   "title": "haproxy_server_up",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "haproxy_server_up" }
   ]
  }
 ]
}