---
- name: install MySQL Exporter
  become: yes
  apt:
    name: prometheus-mysqld-exporter

- name: Config
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify:
    - Systemctl daemon-reload
    - Restart MySQL Exporter

- name: MySQL Exporter user
  mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
  #no_log: True
  #notify: Restart MySQL Exporter

- name: Execute handlers
  meta: flush_handlers

# - name: Wait for a few seconds
#   wait_for:
#     timeout: 20

- name: Enabled
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes