---
- name: Install exporter packages
  apt:
    name: 
      - prometheus-node-exporter
    update_cache: yes

- name: Started
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes