---
 - name: Creating linux users
   user:
     name: juri
     name: roman

 - name: allow ssh authorisation for juri
   authorized_key:
     user: juri
     key: https://github.com/hudolejev.keys
 - name: allow ssh authorisation for roman
   authorized_key:
     user: roman
     key: https://github.com/romankuchin.keys
