---
- name: install uwsgi
  become: yes
  apt:
    name: uwsgi
    state: latest

- name: install uwsgi
  become: yes
  apt:
    name: uwsgi-plugin-python3
    state: latest

- name: install pymysql
  apt:
    name: python3-pymysql
    state: latest   

- name: Create a directory
  file:
    path: /etc/uwsgi/apps-enabled
    state: directory

# - name: add uwsgi config file
#   copy:
#     src: agama.ini
#     dest: /etc/uwsgi/apps-enabled/agama.ini
#   notify: restart uwsgi

- name: Copy uWSGI configuration
  template:
    src: agama.ini.j2
    dest: /etc/uwsgi/apps-enabled/agama.ini
    force: yes
  notify: restart uwsgi

- name: ensure that uwsgi is started
  become: yes
  service:
    name: uwsgi
    state: started
    enabled: yes   