---
- name: Install Nginx
  apt: 
    name: nginx
    update_cache: yes

- name: Nginx config
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: 
    - Restart Nginx

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

# - name: Nginx config
#   template:
#     src: stub_status.j2
#     dest: /etc/nginx/sites-enabled/stub_status
#   notify: 
#     - Restart Nginx