---
  - name: install uwsgi
    become: yes
    apt:
      name: uwsgi
      state: latest

  - name: install uwsgi-plugin-python3
    become: yes
    apt:
      name: uwsgi-plugin-python3
      state: latest

  - name: add uwsgi config file
    copy:
      src: agama.ini
      dst: /etc/uwsgi/apps-enabled/agama.ini
    notify: restart uwsgi

  - name: ensure that uwsgi is enabled
    become: yes
    service:
      name: uwsgi
      enabled: yes

  - name: ensure that uwsgi is started
    become: yes
    service:
      name: uwsgi
      state: started   
