---
- name: Restart Prometheus
  service:
    name: prometheus
    state: restarted

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Systemctl daemon-reload
  shell: "systemctl daemon-reload"    