---
- name: Ensure nginx is installed and in working state
  apt: 
    name: nginx
    state: latest
    update_cache: yes
    
- name: Serve index.html
  copy:
    src: ../files
    dest: /var/www/html
  
- name: Copy Nginx configuration
  copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx

- name: start nginx and make sure it is enabled
  service:
    name: nginx
    state: started
    enabled: yes